### ISSUE TITLE
Need support for network-restricted deploys

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-apache-bigtop-base#42]
The URLs for the Apache Bigtop tarball (for puppet scripts) and apt repo are hard-coded in `layer.yaml` which makes it very difficult to deploy in a network-restricted environment.  A proxy works but sometimes that is not an option.

We should leverage Juju resources for this.

**Comment by johnsca** [comment]
Should we allow falling back to the URLs if the resources aren't provided or if deployed on pre-2.0?

**Comment by kwmonroe** [comment]
Fixed in #58 by adding a `bigtop-repo` resource.  By default, the resource in the store is a zip of the latest tagged release of https://github.com/apache/bigtop.
