### ISSUE TITLE
SPARK stuck in maintenance if benchmarks can't be installed

### ISSUE THREAD

**Issue by erik78se** [juju-solutions/layer-apache-bigtop-base#59]
**What I try to do:** I was trying to showcase a clean installation of hadoop-spark. Defaults on everything.
We have a proxy, but thats taken care of on the model level as such (servernames replaced below):

`juju add-model scania-hadoop-spark --config http-proxy=http://ourinternalproxyserver:8080 --config https-proxy=http://ourinternalproxyserver:8080 --config no-proxy=127.0.0.1` 

This is how I installed the bundle: 
` juju deploy cs:bundle/hadoop-spark-37`

Everything installs OK up until when it tries so start/install spark. Then it gets stuck.

SPARK ends up in a "maintenance" status 

"juju status" gives...

> spark/0*                   maintenance  idle   4        10.54.83.143                        configuring spark in yarn-client mode

**I would expect it to fail into an "error" state here with some useful output telling me what went wrong.**

I have concluded with help from "kjackal" in #juju at freenode IRC that its related to when its not possible to download (proxy!) the benchmarks for spark from AWS s3 buckets, the installation never reaches an error state, but instead gets stuck in "maintenance".

**Comment by erik78se** [comment]
NOTE:

I managed to get out of the error by setting the configuration:

`juju config spark spark_bench_enabled=false`

Then the installation completes and spark enters a "active" state.

**Comment by ktsakalozos** [comment]
Here are some logs from @erik78se 

Deployment matrix of Spark: https://pastebin.com/bqWKGvZE
Juju status: https://pastebin.com/DZey05k0
Stacktrace of the silenced error: https://pastebin.com/4RKMmBqW

**Comment by kwmonroe** [comment]
@erik78se Spark-Bench is now optional and no longer installed by default.  This went in with:

https://issues.apache.org/jira/browse/BIGTOP-2834

spark-51 and above contain this fix:

https://jujucharms.com/spark/

Please let me know if you see any other issues related to spark deployment in a restricted network.  Thanks!
